In [1]:
from planckmc.track_generation import halo_model
from planckmc.track_generation import make_tracks
from planckmc.detector_characteristics import DETECTOR_CHARACTERISTICS
from planckmc.response import sensor_response, RESPONSE_DICT
from planckmc.config import CONFIG
import numpy as np
from numba import njit, jit
%matplotlib widget
import matplotlib # plotting libraries
from matplotlib import animation, rc, cm
import matplotlib.pyplot as plt
import matplotlib.colors as clr
from mpl_toolkits.mplot3d import Axes3D


/home/isparavanje/python_projects/env2/lib/python3.7/site-packages/wimprates/halo.py:144: RuntimeWarning: divide by zero encountered in true_divide
  / (2 * v_earth_t * v))


#### First, we take a quick look at detector characteristics.

In [2]:
DETECTOR_CHARACTERISTICS

{'15ZE': {'position': array([0.1, 0.1, 0. ]), 'orientation': array([[1, 0, 0],
         [0, 1, 0],
         [0, 0, 1]]), 'sensitivity': array([1, 1, 1]), 'noise': array([75, 75, 75])},
 '22FP': {'position': array([ 0.1, -0.1,  0. ]),
  'orientation': array([[1, 0, 0],
         [0, 1, 0],
         [0, 0, 1]]),
  'sensitivity': array([1, 1, 1]),
  'noise': array([75, 75, 75])},
 '14BC': {'position': array([-0.1,  0.1,  0. ]),
  'orientation': array([[1, 0, 0],
         [0, 1, 0],
         [0, 0, 1]]),
  'sensitivity': array([1, 1, 1]),
  'noise': array([75, 75, 75])},
 '79QT': {'position': array([-0.1, -0.1,  0. ]),
  'orientation': array([[1, 0, 0],
         [0, 1, 0],
         [0, 0, 1]]),
  'sensitivity': array([1, 1, 1]),
  'noise': array([75, 75, 75])},
 '8YAC': {'position': array([0. , 0. , 0.1]), 'orientation': array([[1, 0, 0],
         [0, 1, 0],
         [0, 0, 1]]), 'sensitivity': array([1, 1, 1]), 'noise': array([75, 75, 75])},
 'Z453': {'position': array([ 0. ,  0. , -0.1]),

#### Generate 1000 tracks

To do this, first, we generate an array of velocities. Following that, we generate the track entry and exit vectors. We make all tracks start at time=0 for this demonstration. Finally, We generate acceleration from tracks. We then print some values for the zeroth track.

In [3]:
vel = halo_model.generate_vel_array(n_vels=1000)

In [4]:
entry_vecs, exit_vecs, t_entry, t_exit = make_tracks.generate_tracks(vel, np.zeros(vel.shape))

In [5]:
out = make_tracks.generate_acceleration_dict(entry_vecs, exit_vecs, t_entry, t_exit, {'M':2.18e-8, 'G':6.674e-11},)

Timesteps of the zeroth track:

In [6]:
out[0]['time']

array([-500, -400, -300, -200, -100,    0,  100,  200,  300,  400,  500,
        600,  700,  800,  900, 1000, 1100])

truth values of particle location for the zeroth track:

In [7]:
out[0]['particle_location']

array([[-0.01696755,  0.18376771, -0.17716532],
       [-0.01601218,  0.16390835, -0.15215542],
       [-0.01505681,  0.14404898, -0.12714551],
       [-0.01410144,  0.12418962, -0.10213561],
       [-0.01314608,  0.10433025, -0.0771257 ],
       [-0.01219071,  0.08447088, -0.0521158 ],
       [-0.01123534,  0.06461152, -0.02710589],
       [-0.01027997,  0.04475215, -0.00209599],
       [-0.0093246 ,  0.02489279,  0.02291392],
       [-0.00836924,  0.00503342,  0.04792382],
       [-0.00741387, -0.01482595,  0.07293373],
       [-0.0064585 , -0.03468531,  0.09794363],
       [-0.00550313, -0.05454468,  0.12295354],
       [-0.00454776, -0.07440404,  0.14796344],
       [-0.0035924 , -0.09426341,  0.17297335],
       [-0.00263703, -0.11412278,  0.19798325],
       [-0.00168166, -0.13398214,  0.22299316]])

accelerations of the zeroth sensor for the zeroth track:

In [8]:
sensors = tuple(DETECTOR_CHARACTERISTICS.keys())
out[0][sensors[0]]

array([[-1.43161654e-17,  1.02526937e-17, -2.16840321e-17],
       [-2.05610231e-17,  1.13265780e-17, -2.69667465e-17],
       [-3.01658682e-17,  1.15488666e-17, -3.33353125e-17],
       [-4.45493772e-17,  9.44451069e-18, -3.98774771e-17],
       [-6.40198931e-17,  2.45012579e-18, -4.36389792e-17],
       [-8.42280744e-17, -1.16586087e-17, -3.91263536e-17],
       [-9.40452373e-17, -2.99196119e-17, -2.29169988e-17],
       [-8.54646009e-17, -4.28158913e-17, -1.62434568e-18],
       [-6.52221113e-17, -4.48083131e-17,  1.36702442e-17],
       [-4.50278645e-17, -3.94590057e-17,  1.99125456e-17],
       [-3.00129280e-17, -3.20839657e-17,  2.03786972e-17],
       [-2.00593229e-17, -2.53779282e-17,  1.84549185e-17],
       [-1.36750359e-17, -2.00316709e-17,  1.59369110e-17],
       [-9.56462037e-18, -1.59554677e-17,  1.35365320e-17],
       [-6.86727222e-18, -1.28779696e-17,  1.14666241e-17],
       [-5.05352292e-18, -1.05427289e-17,  9.74806969e-18],
       [-3.80277068e-18, -8.75064816e-18

sensor response of the zeroth sensor and zeroth track:

In [9]:
sensor_response(sensors[0], out[0][sensors[0]])

array([[32767, 32768, 32767],
       [32767, 32768, 32767],
       [32767, 32768, 32767],
       [32767, 32768, 32767],
       [32767, 32768, 32767],
       [32767, 32767, 32767],
       [32767, 32767, 32767],
       [32767, 32767, 32767],
       [32767, 32767, 32768],
       [32767, 32767, 32768],
       [32767, 32767, 32768],
       [32767, 32767, 32768],
       [32767, 32767, 32768],
       [32767, 32767, 32768],
       [32767, 32767, 32768],
       [32767, 32767, 32768],
       [32767, 32767, 32768]])

### We then try to plot the magnitude of the accelerations

In [10]:
from IPython.display import HTML

In [11]:
track_i = 0
def animate(i):
    ax2.clear()
    positions = []
    accels = []
    for sensor in DETECTOR_CHARACTERISTICS:
        positions.append(DETECTOR_CHARACTERISTICS[sensor]['position'])
        accels.append(np.linalg.norm(out[track_i][sensor][i]))
    positions = np.array(positions)
    ax2.elev = 30
    ax2.azim = 15
    ax2.set(xlim=[-0.2,0.2],ylim=[-0.2,0.2],zlim=[-0.2,0.2], xlabel='x (cm)', ylabel='y (cm)', zlabel='z (cm)')
    scatter = ax2.scatter(positions.T[0], positions.T[1], positions.T[2], c=accels, s=400, vmin=0, vmax=1e-16, cmap='plasma')
    scatter2 = ax2.scatter(out[track_i]['particle_location'][i,0], out[track_i]['particle_location'][i,1], out[track_i]['particle_location'][i,2], c='r', s=100)
    
    

In [12]:
fig2 = plt.figure(figsize=(12,10))
ax2 = fig2.add_subplot(111, projection='3d')
c = fig2.colorbar(cm.ScalarMappable(norm=clr.Normalize(0,1e-16), cmap='plasma'), ax=ax2)
c.set_label('Acceleration (m/s^2)')
anim = animation.FuncAnimation(fig2, animate,
                               frames=out[track_i][sensors[0]].shape[0],
                               #frames=50,
                               interval=100, blit=False, repeat=True)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [13]:
HTML(anim.to_html5_video())

In [14]:
#anim.save('planck_mass.mp4')