In [113]:
from planckmc.track_generation import halo_model
from planckmc.track_generation import make_tracks
from planckmc.detector_characteristics import DETECTOR_CHARACTERISTICS
from planckmc.response import sensor_response, RESPONSE_DICT
from planckmc.config import CONFIG
import numpy as np
from numba import njit, jit
%matplotlib widget
import matplotlib # plotting libraries
from matplotlib import animation, rc, cm
import matplotlib.pyplot as plt
import matplotlib.colors as clr
from mpl_toolkits.mplot3d import Axes3D

from tqdm import tqdm
from sklearn.preprocessing import MinMaxScaler
from matplotlib.colors import LightSource
#from matplotlib import interactive
#interactive(True)
import matplotlib.image as NonUniformImage
from multihist import Histdd
import numericalunits as nu
from scipy.stats import gaussian_kde
from random import randrange, uniform

import planckanalysis.integral_transform as pint
from random import randrange, uniform

import json

%pdb

Automatic pdb calling has been turned OFF


In [23]:
vel = halo_model.generate_vel_array(n_vels=1)

In [24]:
entry_vecs, exit_vecs, t_entry, t_exit = make_tracks.generate_tracks(vel, np.zeros(vel.shape))

In [25]:
out = make_tracks.generate_acceleration_dict(entry_vecs, exit_vecs, t_entry, t_exit, {'M':2.18e-8, 'G':6.6e-11},)
i=0

In [26]:
out[i]['time']

array([ -500,  -400,  -300,  -200,  -100,     0,   100,   200,   300,
         400,   500,   600,   700,   800,   900,  1000,  1100,  1200,
        1300,  1400,  1500,  1600,  1700,  1800,  1900,  2000,  2100,
        2200,  2300,  2400,  2500,  2600,  2700,  2800,  2900,  3000,
        3100,  3200,  3300,  3400,  3500,  3600,  3700,  3800,  3900,
        4000,  4100,  4200,  4300,  4400,  4500,  4600,  4700,  4800,
        4900,  5000,  5100,  5200,  5300,  5400,  5500,  5600,  5700,
        5800,  5900,  6000,  6100,  6200,  6300,  6400,  6500,  6600,
        6700,  6800,  6900,  7000,  7100,  7200,  7300,  7400,  7500,
        7600,  7700,  7800,  7900,  8000,  8100,  8200,  8300,  8400,
        8500,  8600,  8700,  8800,  8900,  9000,  9100,  9200,  9300,
        9400,  9500,  9600,  9700,  9800,  9900, 10000, 10100, 10200,
       10300, 10400, 10500, 10600, 10700, 10800, 10900, 11000, 11100,
       11200, 11300, 11400, 11500, 11600, 11700, 11800, 11900, 12000,
       12100, 12200,

In [27]:
out[i]['particle_location']

array([[-4.80323516e+00, -1.69951316e+00,  1.52095997e+00],
       [-4.77736110e+00, -1.69097271e+00,  1.52981526e+00],
       [-4.75148704e+00, -1.68243226e+00,  1.53867054e+00],
       [-4.72561298e+00, -1.67389180e+00,  1.54752583e+00],
       [-4.69973891e+00, -1.66535135e+00,  1.55638111e+00],
       [-4.67386485e+00, -1.65681090e+00,  1.56523640e+00],
       [-4.64799079e+00, -1.64827045e+00,  1.57409169e+00],
       [-4.62211673e+00, -1.63972999e+00,  1.58294697e+00],
       [-4.59624267e+00, -1.63118954e+00,  1.59180226e+00],
       [-4.57036860e+00, -1.62264909e+00,  1.60065754e+00],
       [-4.54449454e+00, -1.61410864e+00,  1.60951283e+00],
       [-4.51862048e+00, -1.60556818e+00,  1.61836812e+00],
       [-4.49274642e+00, -1.59702773e+00,  1.62722340e+00],
       [-4.46687236e+00, -1.58848728e+00,  1.63607869e+00],
       [-4.44099830e+00, -1.57994683e+00,  1.64493397e+00],
       [-4.41512423e+00, -1.57140637e+00,  1.65378926e+00],
       [-4.38925017e+00, -1.56286592e+00

In [28]:
sensors = tuple(DETECTOR_CHARACTERISTICS.keys())
out[0][sensors[0]]

array([[-3.07411455e-19,  2.21704057e-19,  7.70723039e-19],
       [-3.02825301e-19,  2.23030977e-19,  7.71786143e-19],
       [-2.98215504e-19,  2.24334591e-19,  7.72773018e-19],
       [-2.93583435e-19,  2.25614552e-19,  7.73683480e-19],
       [-2.88930469e-19,  2.26870525e-19,  7.74517382e-19],
       [-2.84257992e-19,  2.28102189e-19,  7.75274616e-19],
       [-2.79567391e-19,  2.29309233e-19,  7.75955112e-19],
       [-2.74860060e-19,  2.30491363e-19,  7.76558836e-19],
       [-2.70137394e-19,  2.31648294e-19,  7.77085792e-19],
       [-2.65400792e-19,  2.32779757e-19,  7.77536021e-19],
       [-2.60651652e-19,  2.33885496e-19,  7.77909600e-19],
       [-2.55891371e-19,  2.34965269e-19,  7.78206645e-19],
       [-2.51121347e-19,  2.36018845e-19,  7.78427306e-19],
       [-2.46342974e-19,  2.37046011e-19,  7.78571772e-19],
       [-2.41557641e-19,  2.38046565e-19,  7.78640265e-19],
       [-2.36766735e-19,  2.39020321e-19,  7.78633044e-19],
       [-2.31971635e-19,  2.39967105e-19

In [29]:
track = 1
reading_vals_Init = []
tm_vals = []
for sensrs in range(0,len(sensors)):
    x = sensor_response(sensors[sensrs], out[track-1][sensors[sensrs]])
    for tms in range(0,len(out[track-1]['time'])):
        for dim in range(0,len(x[tms])):
            reading_vals_Init.append((x[tms][dim]))

In [30]:
with open('response.json') as file:
  data = json.load(file)

m = np.array(data[sensors[0]]['signal_transfer_response'])

In [31]:
m

array([-1.        , -0.99996948, -0.99993896, ...,  0.99993896,
        0.99996948,  1.        ])

In [174]:
np.array(accels).shape

(64, 369, 3)

In [32]:
m.shape

(65535,)

In [33]:
full_data = np.array([[0] * 3 for i in range(int(len(reading_vals_Init)/3))])

for len_tm in range(0,int(len(reading_vals_Init)/3)):
    for dim in range(0,3):
        l = int(reading_vals_Init[dim + 3*len_tm])
        full_data[len_tm][dim] = l

In [34]:
full_data

array([[33003, 33569, 31963],
       [32233, 32939, 33026],
       [32434, 33860, 32586],
       ...,
       [32757, 32258, 31932],
       [32413, 31593, 32032],
       [32372, 32923, 33602]])

In [35]:
len(out[track-1]['time']) * 64

19648

In [36]:
accels_w_noise = pint.adc_readout_to_accel(full_data, m)

In [37]:
accels_w_noise

array([[ 0.00720237,  0.02447584, -0.02453688],
       [-0.01629688,  0.00524918,  0.00790429],
       [-0.01016266,  0.03335673, -0.00552385],
       ...,
       [-0.00030519, -0.01553392, -0.02548296],
       [-0.01080355, -0.03582873, -0.0224311 ],
       [-0.01205481,  0.00476089,  0.02548296]])

In [38]:
track = 1
reading_vals = []
tm_vals = []

for sensrs in tqdm(range(0,len(sensors))):
    accels_sensor = [[0] * 3 for i in range(len(out[track-1]['time']))]
    for tms in range(0,len(out[track-1]['time'])):
        for dim in range(0,3):
            accels_sensor[tms][dim] = accels_w_noise[tms + (len(out[track-1]['time']) * sensrs)][dim]
        x = sensor_response(sensors[sensrs], np.array(accels_sensor))
        for dim in range(0,len(x[tms])):
            reading_vals.append((x[tms][dim]))
            tm_vals.append(out[track-1]['time'][tms])

100%|██████████| 64/64 [00:58<00:00,  1.10it/s]


In [39]:
len(accels_sensor)

307

In [40]:
smaller_list = []
for zfs in range(0,len(reading_vals)):
    if reading_vals[zfs] < (65536/2)-1:
        smaller_list.append(reading_vals[zfs])

print(len(smaller_list)*100/len(reading_vals))

50.37323561346363


In [53]:
X_Val1 = [-5e2,3.7e4]
Y_Val1 = [(65536/2)-1, (65536/2)-1]

# ADC readout through time, showing how the noise completely overtakes the data

plt.figure(figsize=[12,8])
m2 = Histdd(tm_vals, reading_vals, bins=[np.linspace(-1e3,3.5e4,361),np.logspace(4.49,4.54,301)])
m2.plot(cblabel = 'Count', log_scale = False, cmap = 'viridis')
#plt.hist2d(df['S2'],df['aft'], bins=[np.logspace(1,4.5,200),200], norm=clr.LogNorm())
#plt.plot(df['S2'],df['aft'],'.')
#plt.xlim(-55,55)
#plt.ylim(100,0)
#plt.title()
plt.yscale('log')
plt.plot(X_Val1, Y_Val1, 'r', alpha=0.6, linewidth = 3)
#plt.xscale('log')
plt.ylabel('sensor_readings')
plt.xlabel('time')
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [54]:
track = 1
accls_vals = []
tm_vals_accl = []
for sensrs in range(0,len(sensors)):
    accels_sensor_x = [[0] * 3 for i in range(len(out[track-1]['time']))]
    for tms in range(0,len(out[track-1]['time'])):
        for dim in range(0,3): #len(accels_sensor_x[tms])
            accels_sensor_x[tms][dim] = accels_w_noise[tms + (len(out[track-1]['time']) * sensrs)][dim]
            accls_vals.append((accels_sensor_x[tms][dim]))
            tm_vals_accl.append(out[track-1]['time'][tms] + 50)

In [55]:
len(accls_vals)

58944

In [56]:
64 * len(out[track-1]['time']) * 3

58944

In [57]:
track = 1
accls_vals_sensr = []
tm_vals_sensr = []
sensrs = 22

accels_sensor_sensr = [[0] * 3 for i in range(len(out[track-1]['time']))]
for tms in range(0,len(out[track-1]['time'])):
    for dim in range(0,3): #len(accels_sensor_x[tms])
        accels_sensor_sensr[tms][dim] = accels_w_noise[tms + (len(out[track-1]['time']) * sensrs)][dim]
        accls_vals_sensr.append((accels_sensor_sensr[tms][dim]))
        tm_vals_sensr.append(out[track-1]['time'][tms] + 50)

In [58]:
track = 1
accls_vals_sensr_dimX = []
accls_vals_sensr_dimY = []
accls_vals_sensr_dimZ = []
tm_vals_sensr_dimX = []
tm_vals_sensr_dimY = []
tm_vals_sensr_dimZ = []
sensrs_dims = 22

accels_sensor_sensr_dims = [[0] * 3 for i in range(len(out[track-1]['time']))]
for tms in range(0,len(out[track-1]['time'])):
    for dim in range(0,3): #len(accels_sensor_x[tms])
        accels_sensor_sensr_dims[tms][dim] = accels_w_noise[tms + (len(out[track-1]['time']) * sensrs)][dim]
        accls_vals_sensr_dimX.append((accels_sensor_sensr_dims[tms][0]))
        accls_vals_sensr_dimY.append((accels_sensor_sensr_dims[tms][1]))
        accls_vals_sensr_dimZ.append((accels_sensor_sensr_dims[tms][2]))
        tm_vals_sensr_dimX.append(out[track-1]['time'][tms] + 50)
        tm_vals_sensr_dimY.append(out[track-1]['time'][tms] + 50)
        tm_vals_sensr_dimZ.append(out[track-1]['time'][tms] + 50)

In [59]:
totl_sensr_accel = []
tm_vals_sensr_totl = []
for tms in range(0,len(out[track-1]['time'])):
    totl_sensr_accel.append(accels_sensor_sensr_dims[tms][0] + accels_sensor_sensr_dims[tms][1] + accels_sensor_sensr_dims[tms][2])
    tm_vals_sensr_totl.append(out[track-1]['time'][tms] + 50)

In [62]:
#X_Val1 = [-50000, 70000]
#Y_Val1 = [32000, 32000]

# All sensors, All Dimensions

plt.figure(figsize=[12,8])
#if end point in x bins is 45000, then bins should be 461: (45 + 1)*10 + 1, does not continue on to the hundreds unit (if start is -1000)
#UPDATE- take this: abs(max/min) will give a number, add one, multiply by ten, add one, e.g. 150000/10000 = 15, 15+1= 16, 16*10=160, 160+1=161=bins
m2 = Histdd(tm_vals, accls_vals, bins=[np.linspace(-1000,35000,361),np.linspace(-0.075,0.075,201)])
m2.plot(cblabel = 'Count', log_scale = False, cmap = 'viridis')
#plt.hist2d(df['S2'],df['aft'], bins=[np.logspace(1,4.5,200),200], norm=clr.LogNorm())
#plt.plot(df['S2'],df['aft'],'.')
#plt.xlim(-55,55)
#plt.ylim(100,0)
#plt.title()
#plt.yscale('log')
#plt.plot(X_Val1, Y_Val1, 'r', alpha=0.6, linewidth = 3)
#plt.xscale('log')
plt.ylabel('accels')
plt.xlabel('time')
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [64]:
#X_Val1 = [-50000, 70000]
#Y_Val1 = [32000, 32000]

# All sensors, All Dimensions overlayed with single senser accelerations in all dimensions and the added total acceleration of the sensor

plt.figure(figsize=[12,8])
m2 = Histdd(tm_vals, accls_vals, bins=[np.linspace(-1000,35000,361),np.linspace(-0.075,0.075,201)])
#m3 = Histdd(tm_vals_sensr_dimX, accls_vals_sensr_dimX, bins=[np.linspace(-1000,30000,200),np.linspace(-55e-30,50e-30,200)])
m2.plot(cblabel = 'Count', log_scale = False, cmap = 'viridis')
#m3.plot(cblabel = 'Count', log_scale = False, cmap = 'viridis')
#plt.hist2d(df['S2'],df['aft'], bins=[np.logspace(1,4.5,200),200], norm=clr.LogNorm())
#plt.plot(df['S2'],df['aft'],'.')
#plt.xlim(-55,55)
#plt.ylim(100,0)
#plt.title()
#plt.yscale('log')
plt.plot(tm_vals_sensr_dimX, accls_vals_sensr_dimX, 'r', alpha=1, linewidth = 5, label='X-dim')
plt.plot(tm_vals_sensr_dimY, accls_vals_sensr_dimY, 'g', alpha=1, linewidth = 5, label='Y-dim')
plt.plot(tm_vals_sensr_dimZ, accls_vals_sensr_dimZ, 'w', alpha=1, linewidth = 5, label='Z-dim')
#plt.plot(tm_vals_sensr_totl, totl_sensr_accel, 'b', alpha=1, linewidth = 5, label='Total')
#plt.xscale('log')
plt.ylabel('accels')
plt.xlabel('time')
plt.legend()
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [65]:
plt.figure(figsize=[6,4])
plt.hist(accls_vals, bins = 200)
plt.yscale('log')
plt.ylabel('counts')
plt.xlabel('accels')
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [66]:
analysis_radius = float(CONFIG['Track Generation']['BoundingSphereRadius'])
velocity_bins = np.linspace(1e5,7e5,5)

alphas = pint.generate_alphas(velocity_bins, theta_bin_n=5, phi_bin_n=4, radius=analysis_radius)

In [67]:
i = 0 # track 1
time = out[i]['time']-out[i]['time'][0]
time = np.concatenate([time, time[-1] + np.linspace(0,5000,51, dtype=int)])

strt_indx_len = randrange(0, 60)
strt_accel_pad = np.zeros([strt_indx_len, 3])

end_indx_len = randrange(0, 60)
end_accel_pad = np.zeros([end_indx_len, 3])

accels = []
sensors_pos = []

cnt = 0
for key in out[i]:
    if key not in ['time', 'particle_location']:
        print(key)
        accels_sensor = [[0] * 3 for l in range(len(out[i]['time']))]
        for tms in range(0,len(out[i]['time'])):
            for dim in range(0,3):
                accels_sensor[tms][dim] = accels_w_noise[tms + (len(out[track-1]['time']) * cnt)][dim]
        accels.append(np.concatenate([strt_accel_pad,accels_sensor,end_accel_pad]))
        sensors_pos.append(DETECTOR_CHARACTERISTICS[key]['position'])
        cnt += 1

376011
7D0B2D
FB4128
8B0AE2
A4AA10
2AB43E
D56CB7
003CF3
6F4B57
252744
66B6BF
5813AB
41A7BC
E022C7
E1CA4C
491F88
AA1370
9977ED
955BCC
99F03D
2AE883
3AEF85
BB7AD0
CAFC20
78793D
7E1C05
78D778
D034DB
FC11CC
96059C
1A1977
9BDE29
5407FE
5BF713
9416CD
F60E79
D5874D
AAEEDA
45AF70
813781
39D782
FDEA25
215A39
351210
EA5CD1
2CFF1D
FBD074
060BEC
5178CA
914D90
5C8BE7
143F30
CD295B
ECEFD4
B3E3AA
BA1E8A
7FF751
614FC9
2FFDFC
0CAB7F
1AEB24
C8905C
25A7E0
6F08A6


In [68]:
strt_indx_len

32

In [72]:
accels[0][31]

array([0., 0., 0.])

In [75]:
time

array([    0,   100,   200,   300,   400,   500,   600,   700,   800,
         900,  1000,  1100,  1200,  1300,  1400,  1500,  1600,  1700,
        1800,  1900,  2000,  2100,  2200,  2300,  2400,  2500,  2600,
        2700,  2800,  2900,  3000,  3100,  3200,  3300,  3400,  3500,
        3600,  3700,  3800,  3900,  4000,  4100,  4200,  4300,  4400,
        4500,  4600,  4700,  4800,  4900,  5000,  5100,  5200,  5300,
        5400,  5500,  5600,  5700,  5800,  5900,  6000,  6100,  6200,
        6300,  6400,  6500,  6600,  6700,  6800,  6900,  7000,  7100,
        7200,  7300,  7400,  7500,  7600,  7700,  7800,  7900,  8000,
        8100,  8200,  8300,  8400,  8500,  8600,  8700,  8800,  8900,
        9000,  9100,  9200,  9300,  9400,  9500,  9600,  9700,  9800,
        9900, 10000, 10100, 10200, 10300, 10400, 10500, 10600, 10700,
       10800, 10900, 11000, 11100, 11200, 11300, 11400, 11500, 11600,
       11700, 11800, 11900, 12000, 12100, 12200, 12300, 12400, 12500,
       12600, 12700,

In [81]:
lhk = []
for er in range(time[3],time[-1],700):
    lhk.append(er)
len(lhk)

51

In [82]:
timestep_indices = np.array(range(3,len(time),8)) # The third value is how many indeces are skiped in the time array
timesteps = time[timestep_indices] # Each possible begin time for the track


transformed_data = pint.transform(time/1e9, accels, timesteps/1e9, timestep_indices, alphas, sensors_pos, response_length=2)

100%|██████████| 528/528 [00:10<00:00, 50.76it/s]


In [83]:
# A little over 2 hours to run
alphas.shape

(528, 8)

In [84]:
transformed_data[np.argmax(transformed_data['S_norm'])]

(16.54767824, 0.1880418, 2.10344419, 3.6432722, 3.05648331, 2.67e-05, -4.20688837, 5.15195238e-16, 3.05648331, 6.83373966e-05)

In [85]:
transformed_data

array([(-0.22549781, -0.00071135, -1.60688837, 1.9678707e-16,  4.94549388, 3.00e-07, 2.10344419,  3.6432722,  3.05648331, 3.19141849e-05),
       (-0.65213186, -0.00381364, -1.60688837, 1.9678707e-16,  4.94549388, 3.00e-07, 2.10344419,  3.6432722,  3.05648331, 1.73230226e-05),
       (-0.26540526, -0.00226842, -1.60688837, 1.9678707e-16,  4.94549388, 3.00e-07, 2.10344419,  3.6432722,  3.05648331, 1.19473313e-05),
       ...,
       ( 0.        ,  0.        , -1.60688837, 1.9678707e-16, -4.94549388, 3.46e-05, 2.10344419, -3.6432722, -3.05648331, 5.16230226e-05),
       ( 0.        ,  0.        , -1.60688837, 1.9678707e-16, -4.94549388, 3.46e-05, 2.10344419, -3.6432722, -3.05648331, 4.62473313e-05),
       ( 0.        ,  0.        , -1.60688837, 1.9678707e-16, -4.94549388, 3.46e-05, 2.10344419, -3.6432722, -3.05648331, 4.34519718e-05)],
      dtype=[('S', '<f8'), ('S_norm', '<f8'), ('alpha0_x', '<f8'), ('alpha0_y', '<f8'), ('alpha0_z', '<f8'), ('alpha0_t', '<f8'), ('alpha1_x', '<f8'), ('

In [86]:
np.argmax(transformed_data['S_norm'])

17472

In [87]:
# Entry Time is at 900 ns = 9e-7

In [156]:
Snorm_data_plt = np.array(transformed_data['S_norm'])
S_data_plt = np.array(transformed_data['S'])
tm_data_plt = np.array(transformed_data['alpha0_t'])
np.max(tm_data_plt)

for x in range(0, len(tm_data_plt)):
    if tm_data_plt[x] < -1:
        print('what')

In [157]:
len(tm_data_plt)

23232

In [158]:
max(S_data_plt)

17.065396369672108

In [163]:
transformed_data[np.argmax(S_data_plt)]

(17.06539637, 0.05469678, 2.10344419, 3.6432722, 3.05648331, 4.3e-06, -4.20688837, 5.15195238e-16, 3.05648331, 4.59373966e-05)

In [164]:
transformed_data[np.argmax(Snorm_data_plt) + 1]

(0.38635096, 0.00439035, 2.10344419, 3.6432722, 3.05648331, 2.67e-05, -4.20688837, 5.15195238e-16, 3.05648331, 4.91201366e-05)

In [171]:
accels[0][32]

array([ 0.00720237,  0.02447584, -0.02453688])

In [176]:
X_Val1 = [3.7e-6, 3.7e-6]
Y_Val1 = [-15, 20]

plt.figure(figsize=[6,4])
plt.plot(tm_data_plt, S_data_plt, 'bo', alpha=1)
plt.plot(X_Val1, Y_Val1, 'r', alpha=0.6, linewidth = 3)
#plt.yscale('log')
plt.ylabel('S_norm')
plt.xlabel('entry times')
plt.show()

C:\Users\bahaa\anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  after removing the cwd from sys.path.


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [129]:
np.linspace(0, max(tm_data_plt))

array([0.00000000e+00, 7.06122449e-07, 1.41224490e-06, 2.11836735e-06,
       2.82448980e-06, 3.53061224e-06, 4.23673469e-06, 4.94285714e-06,
       5.64897959e-06, 6.35510204e-06, 7.06122449e-06, 7.76734694e-06,
       8.47346939e-06, 9.17959184e-06, 9.88571429e-06, 1.05918367e-05,
       1.12979592e-05, 1.20040816e-05, 1.27102041e-05, 1.34163265e-05,
       1.41224490e-05, 1.48285714e-05, 1.55346939e-05, 1.62408163e-05,
       1.69469388e-05, 1.76530612e-05, 1.83591837e-05, 1.90653061e-05,
       1.97714286e-05, 2.04775510e-05, 2.11836735e-05, 2.18897959e-05,
       2.25959184e-05, 2.33020408e-05, 2.40081633e-05, 2.47142857e-05,
       2.54204082e-05, 2.61265306e-05, 2.68326531e-05, 2.75387755e-05,
       2.82448980e-05, 2.89510204e-05, 2.96571429e-05, 3.03632653e-05,
       3.10693878e-05, 3.17755102e-05, 3.24816327e-05, 3.31877551e-05,
       3.38938776e-05, 3.46000000e-05])